### ISSUE TITLE
Lyric text for lyric++ doesn't resize correctly when using this theme.

### ISSUE THREAD

**Issue by Mlig317** [darkthemer/rosepine-theme-windows#1]
The lyric app provided by spicetify has a resize font feature that works in with other themes but when using this theme simply spaces the text further apart horizontally (as if invisible text is being resized correctly and this themes text simply is drawing over at the default font size)

**Comment by Mlig317** [comment]
to clarify, by this theme, i mean the text based theme :)

**Comment by darkthemer** [comment]
Please forward this issue to the [Spicetify themes repo](https://github.com/spicetify/spicetify-themes), where the text theme is hosted.
